version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: hihihaha_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hihihaha_db

  postgres:
    image: postgres:16-alpine
    container_name: hihihaha_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hihihaha_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5-community
    container_name: hihihaha_neo4j
    restart: always
    ports:
      - "17474:7474" # map port 17474 tranh hyper-v windows
      - "17687:7687" # map port 17687 tranh hyper-v windows
    environment:
      NEO4J_AUTH: neo4j/neo4j123456
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7.2-alpine
    container_name: hihihaha_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  pg_data:
  neo4j_data:
  redis_data:
